BANDAAV1.View/Models/ErrorViewModel.cs
namespace BANDAAV1.View.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BANDAAV1.View/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BANDAAV1.Model;

namespace BANDAAV1.View.Controllers
{
    public class AlbumController : Controller
    {
        // GET: AlbumController
        BANDASContext db;
        public AlbumController()
        {
            db = new BANDASContext();
        }
        public ActionResult Index()
        {
            List<Tbalbum> oLista = db.Tbalbum.ToList();
            return View(oLista);
        }

        // GET: AlbumController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AlbumController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AlbumController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tbalbum oAlb)
        {
            db.Tbalbum.Add(oAlb);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: AlbumController/Edit/5
        public ActionResult Edit(int id)
        {
            Tbalbum oAlb = db.Tbalbum.Find(id);
            return View(oAlb);
        }

        // POST: AlbumController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Tbalbum oAlb)
        {
            var oAlbBanco = db.Tbalbum.Find(id);
            oAlbBanco.AlbumNome = oAlb.AlbumNome;
            db.Entry(oAlbBanco).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: AlbumController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AlbumController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BANDAAV1.View/Controllers/BandaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BANDAAV1.Model;

namespace BANDAAV1.View.Controllers
{
    public class BandaController : Controller
    {
        // GET: BandaController
        BANDASContext db;
        public BandaController()
        {
            db = new BANDASContext();
        }
        public ActionResult Index()
        {
            List<Tbbanda> oLista = db.Tbbanda.ToList(); 
            return View(oLista);
        }

        // GET: BandaController/Details/5
        public ActionResult Details(int id)
        {
            Tbbanda oBan = db.Tbbanda.Find(id);
            return View(oBan);
        }

        // GET: BandaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BandaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tbbanda oBan)
        {
            db.Tbbanda.Add(oBan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: BandaController/Edit/5
        public ActionResult Edit(int id)
        {
            Tbbanda oBan = db.Tbbanda.Find(id);
            return View(oBan);
        }

        // POST: BandaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Tbbanda oBan)
        {
            var oBanBanco = db.Tbbanda.Find(id);
            oBanBanco.BandaNome = oBan.BandaNome;
            oBanBanco.Bandagenero = oBan.Bandagenero;
            db.Entry(oBanBanco).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: BandaController/Delete/5
        public ActionResult Delete(int id)
        {
            Tbbanda oBan = db.Tbbanda.Find(id);
            return View(oBan);
        }

        // POST: BandaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Tbbanda oBan)
        {
            var oBanBanco = db.Tbbanda.Find(id);
            oBanBanco.BandaNome = oBan.BandaNome;
            oBanBanco.Bandagenero = oBan.Bandagenero;
            db.Entry(oBanBanco).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BANDAAV1.View/Controllers/HomeController.cs
using BANDAAV1.View.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BANDAAV1.View.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BANDAAV1.View/Views/Album/Create.cshtml
@model BANDAAV1.Model.Tbalbum

@{
    ViewData["Title"] = "Incluir";
}

<h1>Incluir Album</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BandaId" class="control-label"></label>
                <select asp-for="BandaId" class ="form-control" asp-items="ViewBag.BandaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="AlbumNome" class="control-label"></label>
                <input asp-for="AlbumNome" class="form-control" />
                <span asp-validation-for="AlbumNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Lista de Albuns</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BANDAAV1.View/Views/Album/Index.cshtml
@model IEnumerable<BANDAAV1.Model.Tbalbum>

@{
    ViewData["Title"] = "View";
}

<h1>Lista de Albuns</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AlbumId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AlbumNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Banda)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AlbumId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AlbumNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Banda.BandaNome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AlbumId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.AlbumId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.AlbumId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BANDAAV1.View/Views/Banda/Create.cshtml
@model BANDAAV1.Model.Tbbanda

@{
    ViewData["Title"] = "Incluir";
}

<h1>Incluir Banda</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BandaNome" class="control-label"></label>
                <input asp-for="BandaNome" class="form-control" />
                <span asp-validation-for="BandaNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bandagenero" class="control-label"></label>
                <input asp-for="Bandagenero" class="form-control" />
                <span asp-validation-for="Bandagenero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Lista de Bandas</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BANDAAV1.View/Views/Banda/Delete.cshtml
@model BANDAAV1.Model.Tbbanda

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar</h1>

<h3>Você está certo disso?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BandaNome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BandaNome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bandagenero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bandagenero)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BandaId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Lista de Bandas</a>
    </form>
</div>

BANDAAV1.View/Views/Banda/Details.cshtml
@model BANDAAV1.Model.Tbbanda

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BandaNome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BandaNome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bandagenero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bandagenero)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BandaId">Edit</a> |
    <a asp-action="Index">Lista de Bandas</a>
</div>

BANDAAV1.View/Views/Banda/Edit.cshtml
@model BANDAAV1.Model.Tbbanda

@{
    ViewData["Title"] = "Alterar";
}

<h1>Alterar Banda</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BandaId" />
            <div class="form-group">
                <label asp-for="BandaNome" class="control-label"></label>
                <input asp-for="BandaNome" class="form-control" />
                <span asp-validation-for="BandaNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bandagenero" class="control-label"></label>
                <input asp-for="Bandagenero" class="form-control" />
                <span asp-validation-for="Bandagenero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Lista de Bandas</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BANDAAV1.View/Views/Banda/Index.cshtml
@model IEnumerable<BANDAAV1.Model.Tbbanda>

@{
    ViewData["Title"] = "View";
}

<h1>Lista de Bandas</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BandaId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BandaNome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bandagenero)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BandaId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BandaNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bandagenero)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BandaId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BandaId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BandaId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BANDAAV1.View/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BANDAAV1.View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BANDAAV1.View</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BANDAAV1.View.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BANDAAV1.View</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Banda" asp-action="Index">Bandas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="Index">Albuns</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BANDAAV1.View - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>